[package]
name = "sitebuilder"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14.2"
clap = { version = "3.1.6", features = ["derive"] }
slog = "2.7.0"
config = "0.12.0"
